# Generated by Django 5.2.3 on 2025-06-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clamps', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='max_single_download_mb',
            field=models.IntegerField(default=50, verbose_name='单次最大下载大小（MB）'),
        ),
    ]
