# Generated by Django 5.2.3 on 2025-06-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clamps', '0004_alter_userprofile_max_single_download_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='max_batch_download_mb',
            field=models.IntegerField(default=200, verbose_name='单次批量下载最大大小（MB）'),
        ),
    ]
