# Generated by Django 5.2.3 on 2025-06-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clamps', '0005_userprofile_max_batch_download_mb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='max_batch_download_mb',
        ),
    ]
