# Generated by Django 5.2.3 on 2025-06-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clamps', '0007_userprofile_max_batch_download_mb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password_validity_days',
            field=models.IntegerField(default=5, help_text='设置为0表示永久有效，1-15表示有效天数', verbose_name='密码有效期（天）'),
        ),
    ]
