# Copyright [2025] [OBARA (Nanjing) Electromechanical Co., Ltd]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.



# Generated by Django 5.2.3 on 2025-06-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clamps', '0007_userprofile_max_batch_download_mb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password_validity_days',
            field=models.IntegerField(default=5, help_text='设置为0表示永久有效，1-15表示有效天数', verbose_name='密码有效期（天）'),
        ),
    ]
