# Copyright [2025] [OBARA (Nanjing) Electromechanical Co., Ltd]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.



# Generated by Django 5.2.3 on 2025-07-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clamps', '0008_alter_userprofile_password_validity_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='max_daily_download_gb',
            field=models.IntegerField(default=100, verbose_name='每日最大下载大小（GB）'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_single_download_mb',
            field=models.IntegerField(default=100, verbose_name='单次最大下载大小（MB）'),
        ),
    ]
