# Generated by Django 5.2.3 on 2025-07-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clamps', '0008_alter_userprofile_password_validity_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='max_daily_download_gb',
            field=models.IntegerField(default=100, verbose_name='每日最大下载大小（GB）'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_single_download_mb',
            field=models.IntegerField(default=100, verbose_name='单次最大下载大小（MB）'),
        ),
    ]
