# Generated by Django 5.2.3 on 2025-07-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clamps', '0009_alter_userprofile_max_daily_download_gb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='密码备注'),
        ),
    ]
