# Generated by Django 5.2.3 on 2025-07-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clamps', '0010_userprofile_password_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_expired_password_login',
            field=models.BooleanField(default=False, help_text='勾选后，密码过期用户无需重置密码即可登录', verbose_name='允许过期密码登录'),
        ),
    ]
