# Copyright [2025] [OBARA (Nanjing) Electromechanical Co., Ltd]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.



# Generated by Django 5.2.3 on 2025-07-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clamps', '0010_userprofile_password_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_expired_password_login',
            field=models.BooleanField(default=False, help_text='勾选后，密码过期用户无需重置密码即可登录', verbose_name='允许过期密码登录'),
        ),
    ]
