# Copyright [2025] [OBARA (Nanjing) Electromechanical Co., Ltd]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.



# Generated by Django 5.2.4 on 2025-07-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clamps', '0011_userprofile_allow_expired_password_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='allow_expired_password_login',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password_remark',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='customer_name',
            field=models.CharField(blank=True, help_text='用于备注客户名称', max_length=255, null=True, verbose_name='客户名称'),
        ),
    ]
