# Generated by Django 5.2.4 on 2025-07-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clamps', '0011_userprofile_allow_expired_password_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='allow_expired_password_login',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password_remark',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='customer_name',
            field=models.CharField(blank=True, help_text='用于备注客户名称', max_length=255, null=True, verbose_name='客户名称'),
        ),
    ]
