# Generated by Django 5.2.5 on 2025-08-26 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clamps', '0012_remove_userprofile_allow_expired_password_login_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='max_daily_download_gb',
            field=models.IntegerField(default=10, verbose_name='每日最大下载大小（GB）'),
        ),
    ]
