# Generated by Django 5.2.3 on 2025-09-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clamps', '0013_userprofile_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdf_file_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PDF文件路径'),
        ),
    ]
