# Copyright [2025] [OBARA (Nanjing) Electromechanical Co., Ltd]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Generated by Django 5.2.3 on 2025-11-30 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clamps', '0014_alter_product_pdf_file_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(help_text='用于生成链接的唯一标识', max_length=32, unique=True, verbose_name='唯一标识符')),
                ('search_config', models.JSONField(default=dict, help_text='JSON格式，存储搜索选项的配置', verbose_name='搜索配置')),
                ('ai_disabled', models.BooleanField(default=True, help_text='是否禁用AI智能搜索', verbose_name='AI智能搜索禁用')),
                ('name', models.CharField(blank=True, help_text='链接的备注名称', max_length=255, null=True, verbose_name='备注名称')),
                ('expires_at', models.DateTimeField(blank=True, help_text='链接过期时间，为空表示永久有效', null=True, verbose_name='有效期')),
                ('click_count', models.IntegerField(default=0, help_text='当前点击次数', verbose_name='点击次数')),
                ('max_clicks', models.IntegerField(default=0, help_text='设置为0表示无限制', verbose_name='最大点击次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '式样链接',
                'verbose_name_plural': '式样链接',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_by',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['drawing_no_1'], name='clamps_prod_drawing_923385_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='clamps_prod_categor_a9b8ba_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sub_category_type'], name='clamps_prod_sub_cat_ae3d81_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['transformer'], name='clamps_prod_transfo_96d9b7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['motor_manufacturer'], name='clamps_prod_motor_m_10a5db_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['has_balance'], name='clamps_prod_has_bal_f93697_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['water_circuit'], name='clamps_prod_water_c_ad2e5d_idx'),
        ),
        migrations.AddField(
            model_name='stylelink',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_links', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
    ]
