# Copyright [2025] [OBARA (Nanjing) Electromechanical Co., Ltd]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Generated by Django 5.2.3 on 2025-12-08 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clamps', '0016_userprofile_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stylelink',
            options={'ordering': ['-created_at'], 'verbose_name': '仕样链接', 'verbose_name_plural': '仕样链接'},
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('数据错误', '数据错误'), ('数据丢失', '数据丢失'), ('系统错误', '系统错误'), ('功能优化', '功能优化'), ('其他建议', '其他建议')], max_length=100, verbose_name='反馈分类')),
                ('related_link', models.URLField(blank=True, max_length=255, null=True, verbose_name='相关链接')),
                ('content', models.TextField(help_text='请详细描述您的问题或建议', verbose_name='内容说明')),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='姓名')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='电话')),
                ('contact_email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('status', models.CharField(choices=[('待确认', '待确认'), ('已确认待处理', '已确认待处理'), ('已处理', '已处理'), ('无法确认', '无法确认'), ('无效反馈', '无效反馈')], default='待确认', max_length=100, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to=settings.AUTH_USER_MODEL, verbose_name='反馈用户')),
            ],
            options={
                'verbose_name': '用户反馈',
                'verbose_name_plural': '用户反馈',
                'ordering': ['-created_at'],
            },
        ),
    ]
