# Copyright [2025] [OBARA (Nanjing) Electromechanical Co., Ltd]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Generated by Django 5.2.3 on 2025-12-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clamps', '0017_alter_stylelink_options_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='is_notified',
            field=models.BooleanField(default=False, verbose_name='是否已通知用户'),
        ),
    ]
