# Generated by Django 5.2.3 on 2025-12-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clamps', '0017_alter_stylelink_options_userfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='is_notified',
            field=models.BooleanField(default=False, verbose_name='是否已通知用户'),
        ),
    ]
