# Generated by Django 5.2.3 on 2025-12-11 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clamps', '0018_userfeedback_is_notified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStyleLinkVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_visited_at', models.DateTimeField(auto_now_add=True, verbose_name='初次访问时间')),
                ('last_visited_at', models.DateTimeField(auto_now=True, verbose_name='上次访问时间')),
                ('visit_count', models.IntegerField(default=1, verbose_name='访问次数')),
                ('is_valid', models.BooleanField(default=True, verbose_name='链接有效状态')),
                ('link_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='链接名称')),
                ('unique_id', models.CharField(max_length=32, verbose_name='链接唯一标识')),
                ('style_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='clamps.stylelink', verbose_name='仕样链接')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_link_visits', to=settings.AUTH_USER_MODEL, verbose_name='访问用户')),
            ],
            options={
                'verbose_name': '用户仕样链接访问记录',
                'verbose_name_plural': '用户仕样链接访问记录',
                'ordering': ['-last_visited_at'],
                'unique_together': {('user', 'style_link')},
            },
        ),
    ]
