# Generated by Django 5.2.3 on 2025-12-17 05:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clamps', '0019_userstylelinkvisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompressionTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_ids', models.TextField(help_text='产品ID列表，用逗号分隔')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF Only'), ('step', 'STEP Only'), ('bmp', 'BMP Only'), ('both', 'PDF and STEP')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('completed', 'COMPLETED'), ('failed', 'FAILED')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='压缩进度，0-100')),
                ('compressed_file_path', models.CharField(blank=True, help_text='压缩文件路径', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, help_text='错误信息', null=True)),
                ('user_id', models.IntegerField(blank=True, help_text='发起任务的用户ID', null=True)),
            ],
            options={
                'verbose_name': '压缩任务',
                'verbose_name_plural': '压缩任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
