# Generated by Django 5.2.3 on 2026-01-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clamps', '0021_userprofile_last_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后活动时间'),
        ),
    ]
