# Generated by Django 5.2.3 on 2026-01-05 03:08

from django.db import migrations


def set_last_activity_to_null(apps, schema_editor):
    """将从未登录过的用户的last_activity设置为null"""
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('clamps', 'UserProfile')
    
    # 获取所有从未登录过的用户
    users_without_login = User.objects.filter(last_login__isnull=True)
    
    # 将这些用户的last_activity设置为null
    UserProfile.objects.filter(user__in=users_without_login).update(last_activity=None)


class Migration(migrations.Migration):

    dependencies = [
        ('clamps', '0022_alter_userprofile_last_activity'),
    ]

    operations = [
        migrations.RunPython(set_last_activity_to_null),
    ]
